config/routes.rb
Rails.application.routes.draw do
  root to: "home#index"

  # Client Methods
  devise_for :users, :controllers => { :registrations => "users/registrations", :sessions => "users/sessions" }
  resources :users do
    resources :jobs, only: [:new, :create, :show, :update, :index]
  end

  resources :procedures
  # get   '/procedure/:id',         to: 'procedures#show', as: 'procedure_show'

  # resources :consents
  get '/consents', to: 'consents#index', as: 'consents'

  get '/procedure/:id/consent/new', to: 'consents#new', as: 'consent_new'
  post '/procedure/:id/consent/create', to: 'consents#create', as: 'create_consent'
  get '/procedure/:id/consent/:consent_id/update', to: 'consents#update', as: 'update_consent'

  get '/procedure/:procedure_id/consent/:consent_id/indications', to: 'consents#indications', as: 'consent_indications'
  get '/procedure/:procedure_id/consent/:consent_id/benefits', to: 'consents#benefits', as: 'consent_benefits'
  get '/procedure/:procedure_id/consent/:consent_id/risks', to: 'consents#risks', as: 'consent_risks'
  get '/procedure/:procedure_id/consent/:consent_id/alternatives', to: 'consents#alternatives', as: 'consent_alternatives'
  get '/procedure/:procedure_id/consent/:consent_id/description', to: 'consents#description', as: 'consent_description'

  post '/contact_us',            to: 'messages#contact_us',            as: 'contact_us'
  post '/mailgun_receive_email', to: 'messages#mailgun_receive_email', as: 'mailgun_receive_email'

  # Proofreader methods
  resources :users, only: [:index]
  resources :messages, only: [:index]
  get   "/users/:id/manage",            to: 'users#manage',            as: "manage_user"
  patch "/users/:id/management_update", to: 'users#management_update', as: "user_management_update"

  get   'all_jobs', to: 'jobs#all_jobs', as: 'all_jobs'
  get   'jobs/:id/manage',         to: 'jobs#manage', as: 'job_manage'
  patch 'jobs/:id/manage_update',  to: 'jobs#manage_update'
  post  'tasks/:id/start',         to: 'tasks#create_timer'
  patch 'timers/:id/end',          to: 'timers#end_timer', as: 'end_timer'
  patch 'tasks/:id/upload',        to: 'tasks#upload_files' # Is this a post route, Only file uploaded as sub element to task
  patch 'tasks/:id/mark_complete', to: 'tasks#mark_complete'
  patch 'jobs/:id/proofreader_message', to: 'jobs#send_client_email'

  # resources :charges, :only => [:new]
  # post '/buy_credits', to: 'charges#buy_credits', as: 'buy_credits'
  
end

app/models/user.rb
class User < ActiveRecord::Base
  after_initialize :set_default_role, :if => :new_record?
  
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :messages
  has_many :jobs
  has_many :timers
  has_many :consents

  validates :name, :presence => true
  
  enum role: [:user, :proofreader, :admin]

  def set_default_role
    self.role ||= :user
  end
  
end

app/controllers/users/confirmations_controller.rb
class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when omniauth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
  before_filter :configure_sign_up_params, only: [:create]
  before_filter :configure_account_update_params, only: [:update]

  skip_before_filter :only_proofreaders!, only: [:edit, :update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  protected

  def configure_sign_up_params
    devise_parameter_sanitizer.for(:sign_up) << [:name, :telephone]
  end

  def configure_account_update_params
    devise_parameter_sanitizer.for(:account_update) << [:name, :telephone]
  end

  # The path used after sign up.
  def after_sign_up_path_for(resource)
    new_user_job_path(resource)
  end

  def after_update_path_for(resource)
    new_user_job_path(resource)
  end

  # TODO: This could be used for a bad credit card or no credits, left this month
  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController
  skip_before_filter :only_proofreaders!, only: [:new, :create, :destroy]
  # before_filter :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  protected

  def after_sign_in_path_for(resource)
    new_user_job_path(resource)
  end

  # You can put the params you want to permit in the empty array.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.for(:sign_in) << :attribute
  # end
end

app/controllers/users/unlocks_controller.rb
class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
    @users = User.all
  end

  def manage
    @user = User.find(params[:id])
    @jobs = @user.jobs.paginate(:page => params[:page], :per_page => 10)
  end

  def management_update
    @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to manage_user_path(@user), :notice => "Profile Updated"
    else
      render 'manage'
    end
  end

  private

    def user_params
      params.require(:user).permit(:internal_bio)
    end
  
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/index.html.erb
<section class="bg-light-gray">
  <div class="container">
    <div class="row">
      <div class="col-md-10">
      <h3>Admin Portal - Listing All Users</h3>
      <table class="table">
        <tr>
          <td>Name</td>
          <td>Internal</td>
          <td>Email</td>
          <td>Telephone</td> 
          <td>Role</td>
        </tr>
        <% @users.each do |user| %>
          <tr>
            <td><%= link_to user.name, user_path(user) %></td>
            <td><%= link_to "Manage", manage_user_path(user) %></td>
            <td><%= user.email %></td>
            <td><%= user.telephone %></td>
            <td><%= user.role %></td>
          </tr>
        <% end %>
      </table>
      </div>
    </div>
  </div>
</section>

app/views/users/manage.html.erb
<section id="upload" class="bg-light-gray">
  <div class="container">

    <div class="row">
      <div class="col-lg-12 text-center">
        <h3 class="section-heading">
          Proofreader's Only - User Management Page
        </h3>
      </div>
    </div>

    <div class="row">
      <div class="col-md-6 col-centered">
        <h4 class="text-center">User: <%=  @user.name if @user.name %></h4>
      </div>
    </div>

    <div class="row">
      <div class="col-md-6 col-centered">
        <%= form_for @user, url: {action: "management_update"}, :html => { :multipart => true }  do |f| %>
          <div class="form-group">
            <%= f.label :internal_bio, "Internal Notes on Client" %>
            <%= f.text_area :internal_bio, class: "form-control" %>
          </div>
          <div class="col-lg-12">
            <%= f.submit("Update", class: "btn btn-primary text-center") %>
          </div>
        <% end %>
      </div>
    </div>

  </div>
</section>

<section id="job-history">
  <div class="container">
    <div class="row">
      <div class="col-xs-12 col-centered">
        <h2 class="section-heading">Job History</h2>
        <h3 class="section-subheading text-muted"></h3>
        <% if !@jobs.any? %>
          <p><em>You have not sent us any messages or documents for proofreading</em>.</p>
        <% else %>
          <div class="panel panel-default">
            <div class="panel-heading">
              <h2 class="panel-title">All Jobs</h2>
              <p class="instructions">Included below are all your proofingreading jobs in the system. Click on any job to view its complete revision hisotry and other details.</p>
            </div>
            <table class="table table-striped table-condensed">
              <thead>
                <tr>
                  <th>Job Title</th>
                  <th>Uploads</th>
                  <th>Downloads</th>
                  <th>Received</th>
                  <th>Compelete</th>
                </tr>
              </thead>
              <tbody>
                <% @jobs.each do |job| %>
                <% message = job.messages.first %>
                  <tr>
                    <td><%= link_to message.subject.truncate(27), job_manage_path(job) %></td>
                    <td>
                      <% job.client_attachments.each do |a| %>
                        <%= link_to a.attachment_file_name, a.attachment.url(:original, false) %><br>
                      <% end %>
                    </td>
                    <td>
                      <% job.finished_attachments.each do |a| %>
                        <%= link_to a.attachment_file_name, a.attachment.url(:original, false) %><br>
                      <% end %>
                    </td>
                    <td><%= job.created_at.strftime("%B %d, %Y at %l:%M%p") %></td>
                    <td><%= job.complete ? job.completed_at.strftime("%B %d, %Y at %l:%M%p") : "" %></td>
                  </tr>
                <% end %>
              </tbody>
            </table>
          </div>
          <%= will_paginate @jobs, renderer: BootstrapPagination::Rails %>
        <% end %>
      </div>
    </div>
  </div>
</section>