config/routes.rb
Rails.application.routes.draw do
  root to: "home#index"

  # Client Methods
  devise_for :users, :controllers => { :registrations => "users/registrations", :sessions => "users/sessions" }
  resources :users do
    resources :jobs, only: [:new, :create, :show, :update, :index]
  end

  resources :procedures
  # get   '/procedure/:id',         to: 'procedures#show', as: 'procedure_show'

  # resources :consents
  get '/consents', to: 'consents#index', as: 'consents'

  get '/procedure/:id/consent/new', to: 'consents#new', as: 'consent_new'
  post '/procedure/:id/consent/create', to: 'consents#create', as: 'create_consent'
  get '/procedure/:id/consent/:consent_id/update', to: 'consents#update', as: 'update_consent'

  get '/procedure/:procedure_id/consent/:consent_id/indications', to: 'consents#indications', as: 'consent_indications'
  get '/procedure/:procedure_id/consent/:consent_id/benefits', to: 'consents#benefits', as: 'consent_benefits'
  get '/procedure/:procedure_id/consent/:consent_id/risks', to: 'consents#risks', as: 'consent_risks'
  get '/procedure/:procedure_id/consent/:consent_id/alternatives', to: 'consents#alternatives', as: 'consent_alternatives'
  get '/procedure/:procedure_id/consent/:consent_id/description', to: 'consents#description', as: 'consent_description'

  post '/contact_us',            to: 'messages#contact_us',            as: 'contact_us'
  post '/mailgun_receive_email', to: 'messages#mailgun_receive_email', as: 'mailgun_receive_email'

  # Proofreader methods
  resources :users, only: [:index]
  resources :messages, only: [:index]
  get   "/users/:id/manage",            to: 'users#manage',            as: "manage_user"
  patch "/users/:id/management_update", to: 'users#management_update', as: "user_management_update"

  get   'all_jobs', to: 'jobs#all_jobs', as: 'all_jobs'
  get   'jobs/:id/manage',         to: 'jobs#manage', as: 'job_manage'
  patch 'jobs/:id/manage_update',  to: 'jobs#manage_update'
  post  'tasks/:id/start',         to: 'tasks#create_timer'
  patch 'timers/:id/end',          to: 'timers#end_timer', as: 'end_timer'
  patch 'tasks/:id/upload',        to: 'tasks#upload_files' # Is this a post route, Only file uploaded as sub element to task
  patch 'tasks/:id/mark_complete', to: 'tasks#mark_complete'
  patch 'jobs/:id/proofreader_message', to: 'jobs#send_client_email'

  # resources :charges, :only => [:new]
  # post '/buy_credits', to: 'charges#buy_credits', as: 'buy_credits'
  
end

app/models/consent.rb
class Consent < ActiveRecord::Base
  belongs_to :user
  belongs_to :procedure

end

app/controllers/consents_controller.rb
class ConsentsController < ApplicationController
  before_action :set_consent, only: [:show, :edit, :update, :destroy]

  respond_to :html

  def index
    # All Consents for the logged in user
    @consents = current_user.consents
    respond_with(@consents)
  end

  def show
    # Status of the current Consent
    respond_with(@consent)
  end

  def new
    # New Consent for a Procedure
    @consent = Consent.new(user_id: current_user.id, procedure_id: params[:id])
    respond_with(@consent)
  end

  # def edit
  # end

  def create
    @consent = Consent.new(consent_params)
    @consent.save!
    redirect_to consent_indications_path(procedure_id: @consent.procedure_id, consent_id: @consent.id)
  end

  def indications
    @consent = Consent.find(params[:consent_id])
    render 'step'
  end  

  def benefits
    @consent = Consent.find(params[:consent_id])
    render 'step'
  end  

  def risks
    @consent = Consent.find(params[:consent_id])
    render 'step'
  end  

  def alternatives
    @consent = Consent.find(params[:consent_id])
    render 'step'
  end  

  def description
    @consent = Consent.find(params[:consent_id])
      render 'step'
  end  

  def update
    @consent = Consent.find(params[:consent_id])
    @consent.send(params[:consent_type]+'_complete=', params[:consent_val])
    @consent.save

    render plain: "success"
  end

  def destroy
    # Cancel Consent
    @consent.destroy
    respond_with(@consent)
  end

  private
    def set_consent
      @consent = Consent.find(params[:id])
    end

    def consent_params
      params.require(:consent).permit(:user_id, :procedure_id, :indications_complete, :benefits_complete, :risks_complete, :alternatives_complete, :description_complete, :consent_complete)
    end
end

app/helpers/consents_helper.rb
module ConsentsHelper

  STEP_ORDER = ["new","indications","benefits","risks","alternatives","description"]

  def previous_step(current)
    result = STEP_ORDER.index(current)
    (result.nil? || result == 0) ? STEP_ORDER[0] : STEP_ORDER[result - 1]
  end

  def next_step(current)
    result = STEP_ORDER.index(current)
    (result.nil? || result == STEP_ORDER.count-1) ? STEP_ORDER.last : STEP_ORDER[result + 1]
  end


end

app/views/consents/_attestation.html.erb
<div class="row">
  <div class="col-sm-offset-1 col-sm-10">
    <div class="panel panel-consent">
      <div class="panel-body">
        <div class="row">
          <div class="col-xs-12">
            <div class="checkbox">
              <label>
                <%=check_box_tag 'consent-checkbox', "1", false%> I attest that I have read the above information in completeness and have no further questions.
              </label>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
  <script>
  $('#consent-checkbox').change(function(){
    $.get("<%=update_consent_path(@consent.procedure_id, @consent.id)%>?consent_type=<%=controller.action_name%>&consent_val="+$(this).val(), function(data,status){
      if(status == 'success'){
        console.log(data)
      }
    })
    $('#consent-checkbox').val($('#consent-checkbox').val() == "1" ? "0" : "1")
  })
  </script>
</div>

app/views/consents/_form.html.erb
<%= form_for(@consent, url: create_consent_path) do |f| %>
  <% if @consent.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@consent.errors.count, "error") %> prohibited this consent from being saved:</h2>

      <ul>
      <% @consent.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :user_id %><br>
    <%= f.number_field :user_id %>
  </div>
  <div class="field">
    <%= f.label :procedure_id %><br>
    <%= f.number_field :procedure_id %>
  </div>
  <div class="field">
    <%= f.label :indications_complete %><br>
    <%= f.check_box :indications_complete %>
  </div>
  <div class="field">
    <%= f.label :benefits_complete %><br>
    <%= f.check_box :benefits_complete %>
  </div>
  <div class="field">
    <%= f.label :risks_complete %><br>
    <%= f.check_box :risks_complete %>
  </div>
  <div class="field">
    <%= f.label :alternatives_complete %><br>
    <%= f.check_box :alternatives_complete %>
  </div>
  <div class="field">
    <%= f.label :description_complete %><br>
    <%= f.check_box :description_complete %>
  </div>
  <div class="field">
    <%= f.label :consent_complete %><br>
    <%= f.check_box :consent_complete %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/consents/edit.html.erb
<h1>Editing consent</h1>

<%= render 'form' %>

<%= link_to 'Show', @consent %> |
<%= link_to 'Back', consents_path %>

app/views/consents/index.html.erb
<section>
  <div class="container">
    <div class="row">
      <div class="col-md-12">
        <div class="panel panel-default">
          <div class="panel-heading">
            <h2 class="panel-title">Your Consents</h2>
            <p class="instructions">Lists all the consents you've started.</p>
          </div>
          <table class="table table-striped table-condensed">
            <thead>
              <tr>
                <th>Status</th>
                <th>Procedure</th>
                <th>Indications complete</th>
                <th>Benefits complete</th>
                <th>Risks complete</th>
                <th>Alternatives complete</th>
                <th>Description complete</th>
                <th>Consent complete</th>
                <th colspan="2"></th>
              </tr>
            </thead>
            <tbody>
              <% @consents.each do |consent| %>
              <tr>
                <td><%= link_to 'Continue', consent %></td>
                <td><%= consent.procedure.name %></td>
                <td><%= consent.indications_complete %></td>
                <td><%= consent.benefits_complete %></td>
                <td><%= consent.risks_complete %></td>
                <td><%= consent.alternatives_complete %></td>
                <td><%= consent.description_complete %></td>
                <td><%= consent.consent_complete %></td>
                <td><%= link_to 'Edit', edit_consent_path(consent) %> | <%= link_to 'Delete', consent, method: :delete, data: { confirm: 'Are you sure?' } %></td>
              </tr>
              <% end %>
            </tbody>
          </table>
        </div>
      </div>
    </div>
  </div>
</section>

app/views/consents/indications.html.erb
<p id="notice"><%= notice %></p>

<section class="small-section bg-light-gray">
  <div class="container">
    <div class="col-lg-12 text-center">
      <h2 class="section-heading"><%= @consent.procedure.name %></h2>
    </div>
    <div class="row">
      <div class="col-sm-offset-1 col-sm-10">
        <div class="panel panel-consent">
          <div class="panel-heading text-center">

            <span class="fa-stack fa-2x pull-left">
              <!-- <i class="fa fa-circle fa-stack-2x text-primary"></i> -->
              <a class="consent-button" href="<%= new_consent_path(@consent.procedure_id) %>">
                <i class="fa fa-arrow-circle-left fa-stack-2x"></i>
              </a>
            </span>
            <h2 class="panel-title text-center">Indications</h2>
            <span class="fa-stack fa-2x pull-right">
              <!-- <i class="fa fa-circle fa-stack-2x text-primary"></i> -->
              <a class="consent-button" href="<%= consent_benefits_path(@consent.procedure_id, @consent.id)%>">
                <i class="fa fa-arrow-circle-right fa-stack-2x"></i>
              </a>
            </span>
            <!-- <p class="instructions">These are details about indications. </p> -->
          </div>
          <div class="panel-body">

            <div class="row">
              <div class="col-xs-12">
                <h3>Information</h3>
                <p><%= @consent.procedure.procedure_detail.indications_text%></p> 
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>

app/views/consents/new.html.erb
<h1>Start New Consent</h1>

<%= render 'form' %>

<%= link_to 'Back', consents_path %>

app/views/consents/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @consent.user_id %>
</p>

<p>
  <strong>Procedure:</strong>
  <%= @consent.procedure_id %>
</p>

<p>
  <strong>Indications complete:</strong>
  <%= @consent.indications_complete %>
</p>

<p>
  <strong>Benefits complete:</strong>
  <%= @consent.benefits_complete %>
</p>

<p>
  <strong>Risks complete:</strong>
  <%= @consent.risks_complete %>
</p>

<p>
  <strong>Alternatives complete:</strong>
  <%= @consent.alternatives_complete %>
</p>

<p>
  <strong>Description complete:</strong>
  <%= @consent.description_complete %>
</p>

<p>
  <strong>Consent complete:</strong>
  <%= @consent.consent_complete %>
</p>

<%= link_to 'Edit', edit_consent_path(@consent) %> |
<%= link_to 'Back', consents_path %>

app/views/consents/step.html.erb
<p id="notice"><%= notice %></p>
<% step = controller.action_name %>

<section class="small-section bg-light-gray">
  <div class="container">
    <div class="col-lg-12 text-center">
      <h2 class="section-heading"><%= @consent.procedure.name %></h2>
    </div>
    <div class="row">
      <div class="col-sm-offset-1 col-sm-10">
        <div class="panel panel-consent">
          <div class="panel-heading text-center">
            <span class="fa-stack fa-2x pull-left">
              <!-- <i class="fa fa-circle fa-stack-2x text-primary"></i> -->
              <a class="consent-button" href="<%= send('consent_'+previous_step(step)+'_path', @consent.procedure_id, @consent.id) %>">
                <i class="fa fa-arrow-circle-left fa-stack-2x"></i>
              </a>
            </span>
            <h2 class="panel-title text-center"><%=step.capitalize%></h2>
            <span class="fa-stack fa-2x pull-right">
              <!-- <i class="fa fa-circle fa-stack-2x text-primary"></i> -->
              <a class="consent-button" href="<%= send('consent_'+next_step(step)+'_path', @consent.procedure_id, @consent.id) %>">
                <i class="fa fa-arrow-circle-right fa-stack-2x"></i>
              </a>
            </span>
            <!-- <p class="instructions">These are details about indications. </p> -->
          </div>
          <div class="row">
            <div class="col-xs-12">
              <h3>Information</h3>
              <p><%= @consent.procedure.procedure_detail.send(step+"_text")%></p> 
            </div>
          </div>
        </div>
      </div>
    </div>
    <%= render 'attestation' %>
  </div>
</section>