config/routes.rb
Rails.application.routes.draw do
  root to: "home#index"

  # Client Methods
  devise_for :users, :controllers => { :registrations => "users/registrations", :sessions => "users/sessions" }
  resources :users do
    resources :jobs, only: [:new, :create, :show, :update, :index]
  end

  resources :procedures
  # get   '/procedure/:id',         to: 'procedures#show', as: 'procedure_show'

  # resources :consents
  get '/consents', to: 'consents#index', as: 'consents'

  get '/procedure/:id/consent/new', to: 'consents#new', as: 'consent_new'
  post '/procedure/:id/consent/create', to: 'consents#create', as: 'create_consent'
  get '/procedure/:id/consent/:consent_id/update', to: 'consents#update', as: 'update_consent'

  get '/procedure/:procedure_id/consent/:consent_id/indications', to: 'consents#indications', as: 'consent_indications'
  get '/procedure/:procedure_id/consent/:consent_id/benefits', to: 'consents#benefits', as: 'consent_benefits'
  get '/procedure/:procedure_id/consent/:consent_id/risks', to: 'consents#risks', as: 'consent_risks'
  get '/procedure/:procedure_id/consent/:consent_id/alternatives', to: 'consents#alternatives', as: 'consent_alternatives'
  get '/procedure/:procedure_id/consent/:consent_id/description', to: 'consents#description', as: 'consent_description'

  post '/contact_us',            to: 'messages#contact_us',            as: 'contact_us'
  post '/mailgun_receive_email', to: 'messages#mailgun_receive_email', as: 'mailgun_receive_email'

  # Proofreader methods
  resources :users, only: [:index]
  resources :messages, only: [:index]
  get   "/users/:id/manage",            to: 'users#manage',            as: "manage_user"
  patch "/users/:id/management_update", to: 'users#management_update', as: "user_management_update"

  get   'all_jobs', to: 'jobs#all_jobs', as: 'all_jobs'
  get   'jobs/:id/manage',         to: 'jobs#manage', as: 'job_manage'
  patch 'jobs/:id/manage_update',  to: 'jobs#manage_update'
  post  'tasks/:id/start',         to: 'tasks#create_timer'
  patch 'timers/:id/end',          to: 'timers#end_timer', as: 'end_timer'
  patch 'tasks/:id/upload',        to: 'tasks#upload_files' # Is this a post route, Only file uploaded as sub element to task
  patch 'tasks/:id/mark_complete', to: 'tasks#mark_complete'
  patch 'jobs/:id/proofreader_message', to: 'jobs#send_client_email'

  # resources :charges, :only => [:new]
  # post '/buy_credits', to: 'charges#buy_credits', as: 'buy_credits'
  
end

app/models/procedure.rb
class Procedure < ActiveRecord::Base
  has_one   :procedure_detail
  has_many :consents

end

app/controllers/procedures_controller.rb
class ProceduresController < ApplicationController
  before_action :set_procedure, only: [:show, :edit, :update, :destroy]

  respond_to :html

  def index
    @procedures = Procedure.all
    respond_with(@procedures)
  end

  def show
    respond_with(@procedure)
  end

  def new
    @procedure = Procedure.new
    respond_with(@procedure)
  end

  def edit
  end

  def create
    @procedure = Procedure.new(procedure_params)
    @procedure.save
    respond_with(@procedure)
  end

  def update
    @procedure.update(procedure_params)
    respond_with(@procedure)
  end

  def destroy
    @procedure.destroy
    respond_with(@procedure)
  end

  private
    def set_procedure
      @procedure = Procedure.find(params[:id])
    end

    def procedure_params
      params.require(:procedure).permit(:name, :slug, :category)
    end
end

app/helpers/procedures_helper.rb
module ProceduresHelper
end

app/views/procedures/_form.html.erb
<%= form_for(@procedure) do |f| %>
  <% if @procedure.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@procedure.errors.count, "error") %> prohibited this procedure from being saved:</h2>

      <ul>
      <% @procedure.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :slug %><br>
    <%= f.text_field :slug %>
  </div>
  <div class="field">
    <%= f.label :category %><br>
    <%= f.text_field :category %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/procedures/edit.html.erb
<h1>Editing procedure</h1>

<%= render 'form' %>

<%= link_to 'Show', @procedure %> |
<%= link_to 'Back', procedures_path %>

app/views/procedures/index.html.erb
<section>
  <div class="container">
    <div class="row">
      <div class="col-md-12">
        <div class="panel panel-default">
          <div class="panel-heading">
            <h2 class="panel-title">All Procedures</h2>
            <p class="instructions">Lists all procedures ready for review.</p>
          </div>
          <table class="table table-striped table-condensed">
            <thead>
              <tr>
                <th>Name</th>
                <th>Category</th>
                <th colspan="3"></th>
              </tr>
            </thead>
            <tbody>
              <% @procedures.each do |procedure| %>
              <tr>
                <td><%= link_to procedure.name, procedure %></td>
                <td><%= procedure.category %></td>
                <td><%= link_to 'Consent', consent_new_path(procedure.id) %></td>
                <td><%= link_to 'Edit', edit_procedure_path(procedure) %></td>
                <td><%= link_to 'Delete', procedure, method: :delete, data: { confirm: 'Are you sure?' } %></td>
              </tr>
              <% end %>
            </tbody>
          </table>
        </div>
        <%= link_to 'New Procedure', new_procedure_path %>
      </div>
    </div>
  </div>
</section>

app/views/procedures/new.html.erb
<h1>New procedure</h1>

<%= render 'form' %>

<%= link_to 'Back', procedures_path %>

app/views/procedures/show.html.erb
<p id="notice"><%= notice %></p>

<section class="small-section bg-light-gray">
  <div class="container">
    <div class="col-lg-12 text-center">
      <h2 class="section-heading"><%= @procedure.name %></h2>
    </div>
    <div class="row">
      <div class="col-sm-offset-1 col-sm-10">
        <div class="panel panel-procedure">
          <div class="panel-heading">
            <h2 class="panel-title">Welcome</h2>
            <p class="instructions">You'll find all the information you need about <%= @procedure.name %> here. </p>
          </div>
          <div class="panel-body">

            <div class="row">
              <div class="col-sm-offset-1 col-sm-5">
                <h3>Procedure Information</h3>
                <p><strong>Name: </strong><%= @procedure.name %></p> 
                <p><strong>Category: </strong><%= @procedure.category %></p> 
                <p><strong>Slug: </strong><%= @procedure.slug %></p> 
                <%= link_to 'Edit', edit_procedure_path(@procedure) %> |
                <%= link_to 'Back', procedures_path %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
</section>