config/routes.rb
Rails.application.routes.draw do
  root to: "home#index"

  # Client Methods
  devise_for :users, :controllers => { :registrations => "users/registrations", :sessions => "users/sessions" }
  resources :users do
    resources :jobs, only: [:new, :create, :show, :update, :index]
  end

  resources :procedures
  # get   '/procedure/:id',         to: 'procedures#show', as: 'procedure_show'

  # resources :consents
  get '/consents', to: 'consents#index', as: 'consents'

  get '/procedure/:id/consent/new', to: 'consents#new', as: 'consent_new'
  post '/procedure/:id/consent/create', to: 'consents#create', as: 'create_consent'
  get '/procedure/:id/consent/:consent_id/update', to: 'consents#update', as: 'update_consent'

  get '/procedure/:procedure_id/consent/:consent_id/indications', to: 'consents#indications', as: 'consent_indications'
  get '/procedure/:procedure_id/consent/:consent_id/benefits', to: 'consents#benefits', as: 'consent_benefits'
  get '/procedure/:procedure_id/consent/:consent_id/risks', to: 'consents#risks', as: 'consent_risks'
  get '/procedure/:procedure_id/consent/:consent_id/alternatives', to: 'consents#alternatives', as: 'consent_alternatives'
  get '/procedure/:procedure_id/consent/:consent_id/description', to: 'consents#description', as: 'consent_description'

  post '/contact_us',            to: 'messages#contact_us',            as: 'contact_us'
  post '/mailgun_receive_email', to: 'messages#mailgun_receive_email', as: 'mailgun_receive_email'

  # Proofreader methods
  resources :users, only: [:index]
  resources :messages, only: [:index]
  get   "/users/:id/manage",            to: 'users#manage',            as: "manage_user"
  patch "/users/:id/management_update", to: 'users#management_update', as: "user_management_update"

  get   'all_jobs', to: 'jobs#all_jobs', as: 'all_jobs'
  get   'jobs/:id/manage',         to: 'jobs#manage', as: 'job_manage'
  patch 'jobs/:id/manage_update',  to: 'jobs#manage_update'
  post  'tasks/:id/start',         to: 'tasks#create_timer'
  patch 'timers/:id/end',          to: 'timers#end_timer', as: 'end_timer'
  patch 'tasks/:id/upload',        to: 'tasks#upload_files' # Is this a post route, Only file uploaded as sub element to task
  patch 'tasks/:id/mark_complete', to: 'tasks#mark_complete'
  patch 'jobs/:id/proofreader_message', to: 'jobs#send_client_email'

  # resources :charges, :only => [:new]
  # post '/buy_credits', to: 'charges#buy_credits', as: 'buy_credits'
  
end

app/views/layouts/_footer.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-4">
    </div>
    <div class="col-md-4">
    </div>
    <div class="col-md-4">
      <span class="copyright">Copyright &copy; 2015</span><br>
    </div>
  </div>
</div>

app/views/layouts/_ga.html.erb
   <script>
//   (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
//   (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
//   m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
//   })(window,document,'script','//www.google-analytics.com/analytics.js','ga');
//   ga('create', "<%= ENV['google_analytics']%>", "<%= ENV['domain']%>");
//   ga('require', 'displayfeatures');
//   ga('send', 'pageview');
 </script>

app/views/layouts/_messages.html.erb
<%# Rails flash messages styled for Bootstrap 3.0 %>
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert-wrapper">
      <div class="alert alert-<%= name.to_s == 'notice' ? 'success' : 'danger' %>">
        <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
        <%= content_tag :div, msg, :id => "flash_#{name}" %>
      </div>
    </div>
  <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-default navbar-fixed-top <%= (params[:controller] == "home") ? "dynamic-header" : "navbar-shrink" %>">
  <div class="container">
<!--     <% if current_user && current_user.proofreader? %>
      <%= link_to "Proofreading", all_jobs_path, id: "proofreader_logged_in" %>
      <% end %> -->
      <!-- Brand and toggle get grouped for better mobile display -->
      <div class="navbar-header page-scroll">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <span class="fa-stack fa-2x pull-left">
          <!-- <i class="fa fa-circle fa-stack-2x text-primary"></i> -->
          <a class="consent-button" href="<%= root_path %>">
            <i class="fa fa-user-md fa-stack-2x"></i>
          </a>
        </span>
        <a class="navbar-brand page-scroll" href="<%= root_path %>"> <%= ENV['company_name'] %></a>
      </div>

      <!-- Collect the nav links, forms, and other content for toggling -->
      <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
        <ul class="nav navbar-nav navbar-right">
          <%= render 'layouts/navigation_links' %>
        </ul>
      </div>
      <!-- /.navbar-collapse -->
    </div>
    <!-- /.container-fluid -->
  </nav>

app/views/layouts/_navigation_links.html.erb
<% if params[:controller] == "home" %>
  <li class="hidden">
    <a href="#page-top"></a>
  </li>
  <li><a class="page-scroll" href="#how-it-works">How it Works</a></li>
<% end %>
  <li><%= link_to 'Procedures', procedures_path %></li>

<% if user_signed_in? %>
  <!-- <li><%= link_to 'Submit Job',  new_user_job_path(current_user) %></li> -->
  <!-- <li><%= link_to 'Job History', user_jobs_path(current_user) %></li> -->
  <li><%= link_to 'Account', edit_user_registration_path %></li>
  <li><%= link_to 'Sign out', destroy_user_session_path, :method=> :delete %></li>
<% else %>
  <li><%= link_to 'Sign Up', new_user_registration_path %></li>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title><%= content_for?(:title) ? yield(:title) : ENV['company_name'] + " | Patient Portal" %></title>
  <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "Professional Proofreading" %>">
  <%= favicon_link_tag 'favicon.ico' %>
  <%= stylesheet_link_tag 'application', media: 'all' %>

  <link href="https://fonts.googleapis.com/css?family=Montserrat:400,700" rel="stylesheet" type="text/css">
  <link href='https://fonts.googleapis.com/css?family=Kaushan+Script' rel='stylesheet' type='text/css'>
  <link href='https://fonts.googleapis.com/css?family=Droid+Serif:400,700,400italic,700italic' rel='stylesheet' type='text/css'>
  <link href='https://fonts.googleapis.com/css?family=Roboto+Slab:400,100,300,700' rel='stylesheet' type='text/css'>

  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
</head>

<body id="page-top">
  
  <main role="main" class="<%= controller.controller_name %>">
    <%= render 'layouts/navigation' %>
    <%= render 'layouts/messages' %>
    <%= yield %>
  </main>

  <footer>
    <%= render 'layouts/footer' %>
  </footer>

  <%= render 'layouts/ga'  %>

  <div class="debug">
    <%= debug(params) if Rails.env.development? %>
  </div>
  
</body>
</html>